services:
  # scrap-knowledge2:
  #   build: ./scrap_knowledge2
  #   container_name: scrap_knowledge2_service
  #   expose:
  #     - "8000"
  #   env_file:
  #     - .env

  frontend:
    build: ./frontend
    container_name: frontend_service
    expose:
      - "3000"
    env_file:
      - .env