version: "3.9"

services:

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - analytics

  analytics:
    build: ./analytics
    container_name: analytics_service
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: frontend_service
    expose:
      - "3000"
    env_file:
      - .env
    depends_on:
      - analytics

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pulse_db
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: