from __future__ import annotations

SOURCES = [
    {"name": "Reuters World", "category": "world", "url": "https://feeds.reuters.com/reuters/worldNews"},
    {"name": "Reuters Business", "category": "business", "url": "https://feeds.reuters.com/reuters/businessNews"},
    {"name": "Associated Press", "category": "world", "url": "https://feedx.net/rss/ap.xml"},
    {"name": "BBC World", "category": "world", "url": "https://feeds.bbci.co.uk/news/world/rss.xml"},
    {"name": "BBC Business", "category": "business", "url": "https://feeds.bbci.co.uk/news/business/rss.xml"},
    {"name": "NPR World", "category": "world", "url": "https://feeds.npr.org/1004/rss.xml"},
    {"name": "NPR Business", "category": "business", "url": "https://feeds.npr.org/1006/rss.xml"},
    {"name": "The Guardian World", "category": "world", "url": "https://www.theguardian.com/world/rss"},
    {"name": "The Guardian Business", "category": "business", "url": "https://www.theguardian.com/uk/business/rss"},
    {"name": "Al Jazeera", "category": "world", "url": "https://www.aljazeera.com/xml/rss/all.xml"},
    {"name": "CNBC World", "category": "business", "url": "https://www.cnbc.com/id/100727362/device/rss/rss.html"},
    {"name": "TechCrunch", "category": "technology", "url": "https://techcrunch.com/feed/"},
    {"name": "Ars Technica", "category": "technology", "url": "https://feeds.arstechnica.com/arstechnica/index"},
]

STOPWORDS = {
    # Small pragmatic stopword set (used by keyword/entity extraction).
    # Keep this intentionally lightweight so domain terms still surface.
    "a",
    "an",
    "and",
    "are",
    "as",
    "at",
    "be",
    "been",
    "by",
    "for",
    "from",
    "has",
    "he",
    "in",
    "is",
    "it",
    "its",
    "of",
    "on",
    "or",
    "that",
    "the",
    "their",
    "this",
    "to",
    "was",
    "were",
    "will",
    "with",
    "after",
    "about",
    "amid",
    "into",
    "than",
    "them",
    "they",
    "his",
    "her",
    "she",
    "you",
    "your",
    "our",
    "who",
    "what",
    "when",
    "where",
    "why",
    "how",
    "not",
    "but",
    "said",
    "says",
    "also",
    "more",
    "first",
    "would",
    "could",
    "should",
}
